### ISSUE TITLE
[Backend] Feat: Create New Poll page 클론해보기

### ISSUE THREAD

**Issue by yeslee-v** [42Seoul-voxotron/voxotron#2]
1. db 명세 대로 ElectionInfo 모델 만들기
2. form으로 ElectionInfo의 필드 입력 받고 ElectionInfo 객체 저장하기
3. 입력값이 잘 저장 되었는지 ElectionInfo 객체 리스트 출력해보기

<img width="637" alt="Screen Shot 2021-12-10 at 9 33 01 PM" src="https://user-images.githubusercontent.com/56112790/145574703-5a857f51-d09f-4535-9a2e-28457b61d41b.png">

**Comment by OctopusET** [comment]
PR not merged
