### ISSUE TITLE
backend: set model of entire user

### ISSUE THREAD

**Issue by Jiwon-Woo** [42Seoul-voxotron/voxotron#22]
- [ ] 유권자 혹은 후보자가 될 수 있는 유저 db 설계
![스크린샷 2022-01-05 오후 9 41 11](https://user-images.githubusercontent.com/74581396/148219255-3fbdc2ce-3381-4171-9cf0-f7f74e5816a1.png)

**Comment by yeslee-v** [comment]
`logins_voters`, `logins_cands` 가 UserInfo와 종속성을 갖기 위해 `Foriegn Key`와 `related_name` 설정

```python

logins_voters = models.ForeignKey(
        UserInfo,
        on_delete=models.CASCADE,
        related_name='logins_voters'
    )
    logins_cands = models.ForeignKey(
        UserInfo,
        on_delete=models.CASCADE,
        related_name='logins_cands'
    )

```
